#libjpeg########################################################################

if(BUNDLED_JPEG)
  set(JPEG_INCLUDES
    libjpeg-turbo-1.3.1/jchuff.h
    libjpeg-turbo-1.3.1/jconfig.h
    libjpeg-turbo-1.3.1/jdct.h
    libjpeg-turbo-1.3.1/jdhuff.h
    libjpeg-turbo-1.3.1/jerror.h
    libjpeg-turbo-1.3.1/jinclude.h
    libjpeg-turbo-1.3.1/jmemsys.h
    libjpeg-turbo-1.3.1/jmorecfg.h
    libjpeg-turbo-1.3.1/jpegint.h
    libjpeg-turbo-1.3.1/jpeglib.h
    libjpeg-turbo-1.3.1/jversion.h)



  set(JPEG_SOURCES
    libjpeg-turbo-1.3.1/jcapimin.c
    libjpeg-turbo-1.3.1/jcapistd.c
    libjpeg-turbo-1.3.1/jctrans.c
    libjpeg-turbo-1.3.1/jcparam.c
    libjpeg-turbo-1.3.1/jdatadst.c
    libjpeg-turbo-1.3.1/jcinit.c
    libjpeg-turbo-1.3.1/jcmaster.c
    libjpeg-turbo-1.3.1/jcmarker.c
    libjpeg-turbo-1.3.1/jcmainct.c
    libjpeg-turbo-1.3.1/jcprepct.c
    libjpeg-turbo-1.3.1/jccoefct.c
    libjpeg-turbo-1.3.1/jcsample.c
    libjpeg-turbo-1.3.1/jchuff.c
    libjpeg-turbo-1.3.1/jcphuff.c
    libjpeg-turbo-1.3.1/jcdctmgr.c
    libjpeg-turbo-1.3.1/jaricom.c
    libjpeg-turbo-1.3.1/jdarith.c
    libjpeg-turbo-1.3.1/jfdctfst.c
    libjpeg-turbo-1.3.1/jfdctflt.c
    libjpeg-turbo-1.3.1/jfdctint.c
    libjpeg-turbo-1.3.1/jdapimin.c
    libjpeg-turbo-1.3.1/jdapistd.c
    libjpeg-turbo-1.3.1/jdtrans.c
    libjpeg-turbo-1.3.1/jdatasrc.c
    libjpeg-turbo-1.3.1/jdmaster.c
    libjpeg-turbo-1.3.1/jdinput.c
    libjpeg-turbo-1.3.1/jdmarker.c
    libjpeg-turbo-1.3.1/jdhuff.c
    libjpeg-turbo-1.3.1/jdphuff.c
    libjpeg-turbo-1.3.1/jdmainct.c
    libjpeg-turbo-1.3.1/jdcoefct.c
    libjpeg-turbo-1.3.1/jdpostct.c
    libjpeg-turbo-1.3.1/jddctmgr.c
    libjpeg-turbo-1.3.1/jidctfst.c
    libjpeg-turbo-1.3.1/jidctflt.c
    libjpeg-turbo-1.3.1/jidctint.c
    libjpeg-turbo-1.3.1/jidctred.c
    libjpeg-turbo-1.3.1/jdsample.c
    libjpeg-turbo-1.3.1/jdcolor.c
    libjpeg-turbo-1.3.1/jquant1.c
    libjpeg-turbo-1.3.1/jquant2.c
    libjpeg-turbo-1.3.1/jdmerge.c
    libjpeg-turbo-1.3.1/jcomapi.c
    libjpeg-turbo-1.3.1/jutils.c
    libjpeg-turbo-1.3.1/jerror.c
    libjpeg-turbo-1.3.1/jmemmgr.c
    libjpeg-turbo-1.3.1/jmemnobs.c
    libjpeg-turbo-1.3.1/jsimd_none.c)

  add_library(jpeg ${JPEG_SOURCES} ${JPEG_INCLUDES})
endif()
